language: node_js
dist: trusty
sudo: false
node_js:
  - '10.7.0'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - ./node_modules

install:
  - yarn

script:
  - export CHROME_BIN=chromium-browser
  - npm run lint:ts
  - npm run test:unit

after_success:
  - codecov
