dist: trusty
language: node_js
sudo: required
node_js:
  - '8.9.4'

branches:
  only:
    - master

install:
  - npm install

script:
  - export CHROME_BIN=chromium-browser
  - npm run lint && npm run test:unit
  - npm run lint

after_success:
  - codecov

cache:
  directories:
    - ./node_modules
