language: node_js

# Force Travis CI to run jobs in VMs instead of Docker containers.
# - https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
# - https://docs.travis-ci.com/user/reference/trusty/#fully-virtualized-via-sudo-required
sudo: required

dist: trusty
node_js:
  - '12.9.0'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - ./node_modules

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.17.3-1

install:
  - yarn

script:
  - export CHROME_BIN=chromium-browser
  - yarn lint
  - yarn test

after_success:
  - codecov
