language: node_js

# Force Travis CI to run jobs in VMs instead of Docker containers.
# - https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
# - https://docs.travis-ci.com/user/reference/trusty/#fully-virtualized-via-sudo-required
sudo: required

dist: trusty
node_js:
  - '11.13.0'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - ./node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - export CHROME_BIN=chromium-browser
  - yarn lint
  - yarn test

after_success:
  - codecov
