dist: trusty
language: node_js
sudo: required
node_js:
  - '9.5.0'

branches:
  only:
    - master

install:
  - npm install

script:
  - export CHROME_BIN=chromium-browser
  - npm run lint
  - npm run test:unit

after_success:
  - codecov

cache:
  directories:
    - ./node_modules
