dist: trusty
language: node_js
sudo: true
node_js:
  - '8.9.3'

branches:
  only:
    - master

install:
  - npm install

script:
  - export CHROME_BIN=chromium-browser
  - npm run lint && npm run test:unit
  - npm run lint
  - codecov

cache:
  directories:
    - ./node_modules
